Add a failsafe for failed binaries installation
Signed-off-by: Eli Uriegas <seemethere101@gmail.com>

diff --git a/deb/build-deb b/deb/build-deb
--- a/deb/build-deb
+++ b/deb/build-deb
@@ -3,6 +3,11 @@ set -x
 # I want to rip this install-binaries script out so badly
 cd engine
 TMP_GOPATH="/go" bash hack/dockerfile/install-binaries.sh runc-dynamic containerd-dynamic proxy-dynamic tini
+if [[ $? -eq 0 ]]; then
+    echo "Binaries required for package building not installed correctly."
+    echo "Exiting..."
+    exit 1
+fi
 cd -
 echo VERSION AAA $VERSION
 
